#!/usr/bin/env python3
"""One-shot helper: inject curated Catalan (`name_ca` / `capital_ca`) columns into the bundled geo
source JSON (countries/rivers/mountains/seas).

Catalan is a well-resourced Romance language, so coverage here is intentionally near-complete and
professional. The few genuine gaps (where the Catalan exonym is identical to the English/Spanish form
that already resolves through the ca → es-ES → en fallback chain) are simply omitted rather than
duplicated. Keys are inserted positionally right after the corresponding `_es_es` column so the JSON
diff stays readable.

Idempotent: re-running overwrites the `_ca` columns from the tables below. Run once via
`python3 scripts/add-catalan-geo.py`; the canonical pack is then produced by `just geo-packs`.
"""

from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCES = REPO_ROOT / "Hanahuac" / "Resources"

# Country name (ca) keyed by ISO id. Only entries whose Catalan exonym differs meaningfully from the
# English base are listed; the rest fall back through ca → es-ES → en.
COUNTRY_NAME_CA = {
    "DZ": "Algèria",
    "AO": "Angola",
    "BJ": "Benín",
    "BW": "Botswana",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Cap Verd",
    "CM": "Camerun",
    "CF": "República Centreafricana",
    "TD": "Txad",
    "KM": "Comores",
    "CD": "República Democràtica del Congo",
    "DJ": "Djibouti",
    "EG": "Egipte",
    "GQ": "Guinea Equatorial",
    "ER": "Eritrea",
    "SZ": "Eswatini",
    "ET": "Etiòpia",
    "GA": "Gabon",
    "GM": "Gàmbia",
    "GH": "Ghana",
    "GN": "Guinea",
    "GW": "Guinea Bissau",
    "CI": "Costa d'Ivori",
    "KE": "Kenya",
    "LS": "Lesotho",
    "LR": "Libèria",
    "LY": "Líbia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "ML": "Mali",
    "MR": "Mauritània",
    "MU": "Maurici",
    "MA": "Marroc",
    "MZ": "Moçambic",
    "NA": "Namíbia",
    "NE": "Níger",
    "NG": "Nigèria",
    "CG": "República del Congo",
    "RW": "Ruanda",
    "ST": "São Tomé i Príncipe",
    "SN": "Senegal",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SO": "Somàlia",
    "ZA": "Sud-àfrica",
    "SS": "Sudan del Sud",
    "SD": "Sudan",
    "TZ": "Tanzània",
    "TG": "Togo",
    "TN": "Tunísia",
    "UG": "Uganda",
    "ZM": "Zàmbia",
    "ZW": "Zimbàbue",
    "AF": "Afganistan",
    "AM": "Armènia",
    "AZ": "Azerbaidjan",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BT": "Bhutan",
    "BN": "Brunei",
    "KH": "Cambodja",
    "CN": "Xina",
    "CY": "Xipre",
    "GE": "Geòrgia",
    "IN": "Índia",
    "ID": "Indonèsia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IL": "Israel",
    "JP": "Japó",
    "JO": "Jordània",
    "KZ": "Kazakhstan",
    "KW": "Kuwait",
    "KG": "Kirguizistan",
    "LA": "Laos",
    "LB": "Líban",
    "MY": "Malàisia",
    "MV": "Maldives",
    "MN": "Mongòlia",
    "MM": "Myanmar",
    "NP": "Nepal",
    "KP": "Corea del Nord",
    "OM": "Oman",
    "PK": "Pakistan",
    "PH": "Filipines",
    "PS": "Palestina",
    "QA": "Qatar",
    "SA": "Aràbia Saudita",
    "SG": "Singapur",
    "KR": "Corea del Sud",
    "LK": "Sri Lanka",
    "SY": "Síria",
    "TW": "Taiwan",
    "TJ": "Tadjikistan",
    "TH": "Tailàndia",
    "TL": "Timor Oriental",
    "TR": "Turquia",
    "TM": "Turkmenistan",
    "AE": "Emirats Àrabs Units",
    "UZ": "Uzbekistan",
    "VN": "Vietnam",
    "YE": "Iemen",
    "AL": "Albània",
    "AD": "Andorra",
    "AT": "Àustria",
    "BY": "Bielorússia",
    "BE": "Bèlgica",
    "BA": "Bòsnia i Hercegovina",
    "BG": "Bulgària",
    "HR": "Croàcia",
    "CZ": "Txèquia",
    "DK": "Dinamarca",
    "EE": "Estònia",
    "FI": "Finlàndia",
    "FR": "França",
    "DE": "Alemanya",
    "GR": "Grècia",
    "HU": "Hongria",
    "IS": "Islàndia",
    "IE": "Irlanda",
    "IT": "Itàlia",
    "XK": "Kosovo",
    "LV": "Letònia",
    "LI": "Liechtenstein",
    "LT": "Lituània",
    "LU": "Luxemburg",
    "MT": "Malta",
    "MD": "Moldàvia",
    "MC": "Mònaco",
    "ME": "Montenegro",
    "NL": "Països Baixos",
    "MK": "Macedònia del Nord",
    "NO": "Noruega",
    "PL": "Polònia",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Rússia",
    "SM": "San Marino",
    "RS": "Sèrbia",
    "SK": "Eslovàquia",
    "SI": "Eslovènia",
    "ES": "Espanya",
    "SE": "Suècia",
    "CH": "Suïssa",
    "UA": "Ucraïna",
    "GB": "Regne Unit",
    "VA": "Ciutat del Vaticà",
    "AG": "Antigua i Barbuda",
    "BS": "Bahames",
    "BB": "Barbados",
    "BZ": "Belize",
    "CA": "Canadà",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "SV": "El Salvador",
    "GD": "Grenada",
    "GT": "Guatemala",
    "HT": "Haití",
    "HN": "Hondures",
    "JM": "Jamaica",
    "MX": "Mèxic",
    "NI": "Nicaragua",
    "PA": "Panamà",
    "KN": "Saint Kitts i Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent i les Grenadines",
    "TT": "Trinitat i Tobago",
    "US": "Estats Units",
    "AU": "Austràlia",
    "FJ": "Fiji",
    "KI": "Kiribati",
    "MH": "Illes Marshall",
    "FM": "Micronèsia",
    "NR": "Nauru",
    "NZ": "Nova Zelanda",
    "PW": "Palau",
    "PG": "Papua Nova Guinea",
    "WS": "Samoa",
    "SB": "Illes Salomó",
    "TO": "Tonga",
    "TV": "Tuvalu",
    "VU": "Vanuatu",
    "AR": "Argentina",
    "BO": "Bolívia",
    "BR": "Brasil",
    "CL": "Xile",
    "CO": "Colòmbia",
    "EC": "Equador",
    "GY": "Guyana",
    "PY": "Paraguai",
    "PE": "Perú",
    "SR": "Surinam",
    "UY": "Uruguai",
    "VE": "Veneçuela",
}

# Capital (ca) keyed by ISO id. Listed where the Catalan form differs from the English base.
CAPITAL_CA = {
    "DZ": "Alger",
    "AO": "Luanda",
    "BJ": "Porto Novo",
    "CV": "Praia",
    "CM": "Yaoundé",
    "CF": "Bangui",
    "TD": "N'Djamena",
    "CD": "Kinshasa",
    "DJ": "Djibouti",
    "EG": "El Caire",
    "ET": "Addis Abeba",
    "GH": "Accra",
    "CI": "Yamoussoukro",
    "KE": "Nairobi",
    "LY": "Trípoli",
    "MR": "Nouakchott",
    "MA": "Rabat",
    "MZ": "Maputo",
    "NE": "Niamey",
    "CG": "Brazzaville",
    "RW": "Kigali",
    "ST": "São Tomé",
    "SO": "Mogadiscio",
    "ZA": "Pretòria",
    "SD": "Khartum",
    "TZ": "Dodoma",
    "TN": "Tunis",
    "AF": "Kabul",
    "AM": "Erevan",
    "AZ": "Bakú",
    "BD": "Dacca",
    "KH": "Phnom Penh",
    "CN": "Pequín",
    "CY": "Nicòsia",
    "GE": "Tbilissi",
    "IN": "Nova Delhi",
    "ID": "Jakarta",
    "IR": "Teheran",
    "IQ": "Bagdad",
    "IL": "Jerusalem",
    "JP": "Tòquio",
    "JO": "Amman",
    "KW": "Kuwait",
    "KG": "Bixkek",
    "LB": "Beirut",
    "MY": "Kuala Lumpur",
    "MN": "Ulan Bator",
    "MM": "Naypyidaw",
    "NP": "Katmandú",
    "KP": "Pyongyang",
    "PK": "Islamabad",
    "PH": "Manila",
    "PS": "Ramal·lah",
    "SA": "Riad",
    "SG": "Singapur",
    "KR": "Seül",
    "SY": "Damasc",
    "TW": "Taipei",
    "TH": "Bangkok",
    "TL": "Dili",
    "TR": "Ankara",
    "AE": "Abu Dhabi",
    "UZ": "Taixkent",
    "VN": "Hanoi",
    "YE": "Sanà",
    "AL": "Tirana",
    "AD": "Andorra la Vella",
    "AT": "Viena",
    "BY": "Minsk",
    "BE": "Brussel·les",
    "BA": "Sarajevo",
    "BG": "Sofia",
    "HR": "Zagreb",
    "CZ": "Praga",
    "DK": "Copenhaguen",
    "EE": "Tallinn",
    "FI": "Hèlsinki",
    "FR": "París",
    "DE": "Berlín",
    "GR": "Atenes",
    "HU": "Budapest",
    "IS": "Reykjavík",
    "IE": "Dublín",
    "IT": "Roma",
    "XK": "Pristina",
    "LV": "Riga",
    "LT": "Vílnius",
    "LU": "Luxemburg",
    "MT": "La Valletta",
    "MD": "Chișinău",
    "MC": "Mònaco",
    "ME": "Podgorica",
    "NL": "Amsterdam",
    "MK": "Skopje",
    "NO": "Oslo",
    "PL": "Varsòvia",
    "PT": "Lisboa",
    "RO": "Bucarest",
    "RU": "Moscou",
    "SM": "San Marino",
    "RS": "Belgrad",
    "SK": "Bratislava",
    "SI": "Ljubljana",
    "ES": "Madrid",
    "SE": "Estocolm",
    "CH": "Berna",
    "UA": "Kíiv",
    "GB": "Londres",
    "VA": "Ciutat del Vaticà",
    "BS": "Nassau",
    "BZ": "Belmopan",
    "CA": "Ottawa",
    "CR": "San José",
    "CU": "L'Havana",
    "DO": "Santo Domingo",
    "SV": "San Salvador",
    "GT": "Ciutat de Guatemala",
    "HT": "Port-au-Prince",
    "HN": "Tegucigalpa",
    "JM": "Kingston",
    "MX": "Ciutat de Mèxic",
    "NI": "Managua",
    "PA": "Ciutat de Panamà",
    "TT": "Port of Spain",
    "US": "Washington DC",
    "AU": "Canberra",
    "FJ": "Suva",
    "MH": "Majuro",
    "NZ": "Wellington",
    "PG": "Port Moresby",
    "SB": "Honiara",
    "VU": "Port Vila",
    "AR": "Buenos Aires",
    "BO": "Sucre",
    "BR": "Brasília",
    "CL": "Santiago",
    "CO": "Bogotà",
    "EC": "Quito",
    "GY": "Georgetown",
    "PY": "Asunción",
    "PE": "Lima",
    "SR": "Paramaribo",
    "UY": "Montevideo",
    "VE": "Caracas",
}

RIVER_NAME_CA = {
    "nile": "Nil",
    "amazon": "Amazones",
    "yangtze": "Iang-Tsé",
    "mississippi": "Mississipí",
    "yenisei": "Ienissei",
    "yellow-river": "Riu Groc",
    "ob": "Obi",
    "congo": "Congo",
    "lena": "Lena",
    "niger": "Níger",
    "mekong": "Mekong",
    "missouri": "Missouri",
    "volga": "Volga",
    "zambezi": "Zambeze",
    "ganges": "Ganges",
    "indus": "Indus",
    "murray": "Murray",
    "euphrates": "Eufrates",
    "tigris": "Tigris",
    "rhine": "Rin",
    "danube": "Danubi",
    "colorado": "Colorado",
    "columbia": "Columbia",
    "irrawaddy": "Irauadi",
    "orange": "Orange",
    "parana": "Paranà",
    "amur": "Amur",
    "dnieper": "Dnièper",
    "senegal-river": "Senegal",
    "orinoco": "Orinoco",
    "sao-francisco": "São Francisco",
    "tocantins": "Tocantins",
}

MOUNTAIN_NAME_CA = {
    "himalayas": "Himàlaia",
    "andes": "Andes",
    "rockies": "Muntanyes Rocalloses",
    "alps": "Alps",
    "great-dividing-range": "Gran Serralada Divisòria",
    "kunlun": "Kunlun",
    "tian-shan": "Tian Shan",
    "altai": "Altai",
    "caucasus": "Caucas",
    "pyrenees": "Pirineus",
    "carpathians": "Carpats",
    "appalachians": "Apalatxes",
    "atlas": "Atles",
    "drakensberg": "Drakensberg",
    "ethiopian-highlands": "Altiplà Etíop",
    "scandinavian-mountains": "Alps Escandinaus",
    "hindu-kush": "Hindu Kush",
    "karakoram": "Karakoram",
    "pamir": "Pamir",
    "sierra-nevada-us": "Sierra Nevada",
    "southern-alps": "Alps del Sud",
    "zagros": "Zagros",
    "eastern-rift-highlands": "Altiplans de la Vall del Rift",
}

SEA_NAME_CA = {
    "pacific": "Oceà Pacífic",
    "atlantic": "Oceà Atlàntic",
    "indian": "Oceà Índic",
    "southern": "Oceà Antàrtic",
    "arctic": "Oceà Àrtic",
    "mediterranean": "Mar Mediterrània",
    "caribbean": "Mar Carib",
    "south-china": "Mar de la Xina Meridional",
    "bering": "Mar de Bering",
    "gulf-of-mexico": "Golf de Mèxic",
    "north-sea": "Mar del Nord",
    "red-sea": "Mar Roja",
    "black-sea": "Mar Negra",
    "caspian-sea": "Mar Càspia",
    "persian-gulf": "Golf Pèrsic",
    "east-china": "Mar de la Xina Oriental",
    "bay-of-bengal": "Golf de Bengala",
    "arabian-sea": "Mar d'Aràbia",
    "coral-sea": "Mar del Corall",
    "tasman-sea": "Mar de Tasman",
}


def _insert_after(item: dict, anchor: str, key: str, value: str) -> OrderedDict[str, object]:
    """Return an OrderedDict with `key`=value inserted immediately after `anchor` (or appended)."""
    out: OrderedDict[str, object] = OrderedDict()
    inserted = False
    for k, v in item.items():
        if k == key:
            continue  # drop any prior value; we re-add positionally below
        out[k] = v
        if k == anchor:
            out[key] = value
            inserted = True
    if not inserted:
        out[key] = value
    return out


def _write(name: str, items: list) -> None:
    text = json.dumps(items, ensure_ascii=False, indent=2) + "\n"
    (RESOURCES / name).write_text(text, encoding="utf-8")
    print(f"updated {name} ({len(items)} records)")


def main() -> None:
    countries = json.load((RESOURCES / "countries.json").open(encoding="utf-8"))
    rebuilt = []
    for c in countries:
        cid = c["id"]
        item = OrderedDict(c)
        if cid in COUNTRY_NAME_CA:
            item = _insert_after(item, "name_es_es", "name_ca", COUNTRY_NAME_CA[cid])
        if cid in CAPITAL_CA:
            item = _insert_after(item, "capital_es_es", "capital_ca", CAPITAL_CA[cid])
        rebuilt.append(item)
    _write("countries.json", rebuilt)

    for fname, table in (
        ("rivers.json", RIVER_NAME_CA),
        ("mountains.json", MOUNTAIN_NAME_CA),
        ("seas.json", SEA_NAME_CA),
    ):
        items = json.load((RESOURCES / fname).open(encoding="utf-8"))
        rebuilt = []
        for it in items:
            item = OrderedDict(it)
            if it["id"] in table:
                item = _insert_after(item, "name_es_es", "name_ca", table[it["id"]])
            rebuilt.append(item)
        _write(fname, rebuilt)


if __name__ == "__main__":
    main()
