#!/usr/bin/env bash
# install-hooks.sh — register this repo's committed git hooks into .git/hooks.
#
# Git hooks are not version-controlled, so a fresh clone must run this once (or `just install-hooks`)
# to activate the secret-scanning pre-commit hook. Idempotent: re-running overwrites the shim.
set -euo pipefail

# Resolve the repository root from this script's location so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

HOOKS_DIR="$(git -C "${REPO_ROOT}" rev-parse --git-path hooks)"
PRE_COMMIT="${HOOKS_DIR}/pre-commit"
TARGET="scripts/hooks/pre-commit-secret-scan.sh"

mkdir -p "${HOOKS_DIR}"

# Install a thin shim that delegates to the committed, version-controlled script. A shim (rather than
# a symlink) keeps the active hook working on filesystems without symlink support and means hook
# logic edits flow through the committed file with no reinstall.
cat > "${PRE_COMMIT}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit. Delegates to the committed hook.
exec "\$(git rev-parse --show-toplevel)/${TARGET}" "\$@"
EOF
chmod +x "${PRE_COMMIT}"

echo "Installed pre-commit hook -> ${TARGET}"
echo "  active at: ${PRE_COMMIT}"
