#!/usr/bin/env bash
# install-hooks.sh — register this repo's committed git hooks into .git/hooks.
#
# Git hooks are not version-controlled, so a fresh clone must run this once (or `just install-hooks`)
# to activate the secret-scanning pre-commit hook. Idempotent: re-running overwrites the shim.
set -euo pipefail

# Resolve the repository root from this script's location so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Resolve the hooks dir as an ABSOLUTE path so the backup/marker checks below are CWD-independent
# (`rev-parse --git-path` can return a path relative to the repo root).
HOOKS_DIR="$(git -C "${REPO_ROOT}" rev-parse --absolute-git-dir)/hooks"
PRE_COMMIT="${HOOKS_DIR}/pre-commit"
TARGET="scripts/hooks/pre-commit-secret-scan.sh"
# Absolute path to the committed hook script, baked into the shim below.
TARGET_ABS="${REPO_ROOT}/${TARGET}"

# Marker that identifies a shim WE installed, so re-running is idempotent and we never back up our own
# previously-installed shim as if it were a user's hand-written hook.
readonly SHIM_MARKER="Auto-generated by scripts/install-hooks.sh"

mkdir -p "${HOOKS_DIR}"

# Preserve a pre-existing, non-shim hook instead of silently clobbering it. If the existing pre-commit
# is one of our own shims (contains the marker), just overwrite it. Otherwise it is a real hook the
# user wrote — back it up to a timestamped sibling and warn.
if [[ -e "${PRE_COMMIT}" ]] && ! grep -qF "${SHIM_MARKER}" "${PRE_COMMIT}" 2>/dev/null; then
    backup="${PRE_COMMIT}.backup.$(date +%Y%m%d%H%M%S)"
    cp -p "${PRE_COMMIT}" "${backup}"
    echo "WARNING: an existing non-shim pre-commit hook was found." >&2
    echo "         Backed it up to: ${backup}" >&2
    echo "         Merge any custom logic into ${TARGET} if you need it to keep running." >&2
fi

# Install a thin shim that delegates to the committed, version-controlled script. A shim (rather than
# a symlink) keeps the active hook working on filesystems without symlink support and means hook
# logic edits flow through the committed file with no reinstall.
#
# Bake the already-resolved ABSOLUTE path into the shim rather than recomputing the repo root at
# hook-run time with `git rev-parse --show-toplevel`: under git worktrees that command resolves to the
# *current* worktree, which may not contain the committed hook script and is fragile during operations
# that change CWD. The absolute path computed here is stable.
cat > "${PRE_COMMIT}" <<EOF
#!/usr/bin/env bash
# ${SHIM_MARKER} — do not edit. Delegates to the committed hook.
exec "${TARGET_ABS}" "\$@"
EOF
chmod +x "${PRE_COMMIT}"

echo "Installed pre-commit hook -> ${TARGET}"
echo "  active at: ${PRE_COMMIT}"
