#!/usr/bin/env python3
"""Durable (idempotent): seed Serbian (Cyrillic) geo columns into the bundled geo JSON.

Adds ``name_sr`` (and ``capital_sr`` for countries) to EVERY entity in
``countries.json``/``rivers.json``/``mountains.json``/``seas.json`` — Serbian is a
COMPLETE-content language, so coverage is total (zero gaps; the sr -> en fallback is a
never-hit safety net).

All values are authored in Serbian CYRILLIC (the constitutionally designated official script
of Serbian), using established Serbian exonyms where they exist (Немачка, Шпанија, Русија,
Москва, Лондон, Пекинг, Средоземно море, Алпи, Дунав, Рајна, …) and transcribed/native names
where Serbian has no distinct exonym. The maps below are keyed by the entity id, so the values
are explicit and reviewable.

Idempotent: re-running rewrites the sr columns from the same source maps. The ``name_sr`` key
is inserted immediately after ``name_nl`` (and ``capital_sr`` after ``capital_nl``) so the
JSON stays readable and the sr columns sit adjacent to the other per-language columns.

Usage:
    python3 scripts/seed-sr-geo.py
"""

from __future__ import annotations

import json
import sys
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCES = REPO_ROOT / "Hanahuac" / "Resources"

# --- Countries: id -> Serbian (Cyrillic) name -----------------------------------------------
COUNTRY_NAME_SR: dict[str, str] = {
    # Africa
    "DZ": "Алжир",
    "AO": "Ангола",
    "BJ": "Бенин",
    "BW": "Боцвана",
    "BF": "Буркина Фасо",
    "BI": "Бурунди",
    "CV": "Зеленортска Острва",
    "CM": "Камерун",
    "CF": "Централноафричка Република",
    "TD": "Чад",
    "KM": "Коморска Острва",
    "CD": "Демократска Република Конго",
    "DJ": "Џибути",
    "EG": "Египат",
    "GQ": "Екваторијална Гвинеја",
    "ER": "Еритреја",
    "SZ": "Есватини",
    "ET": "Етиопија",
    "GA": "Габон",
    "GM": "Гамбија",
    "GH": "Гана",
    "GN": "Гвинеја",
    "GW": "Гвинеја Бисао",
    "CI": "Обала Слоноваче",
    "KE": "Кенија",
    "LS": "Лесото",
    "LR": "Либерија",
    "LY": "Либија",
    "MG": "Мадагаскар",
    "MW": "Малави",
    "ML": "Мали",
    "MR": "Мауританија",
    "MU": "Маурицијус",
    "MA": "Мароко",
    "MZ": "Мозамбик",
    "NA": "Намибија",
    "NE": "Нигер",
    "NG": "Нигерија",
    "CG": "Конго",
    "RW": "Руанда",
    "ST": "Сао Томе и Принципе",
    "SN": "Сенегал",
    "SC": "Сејшели",
    "SL": "Сијера Леоне",
    "SO": "Сомалија",
    "ZA": "Јужноафричка Република",
    "SS": "Јужни Судан",
    "SD": "Судан",
    "TZ": "Танзанија",
    "TG": "Того",
    "TN": "Тунис",
    "UG": "Уганда",
    "ZM": "Замбија",
    "ZW": "Зимбабве",
    # Asia
    "AF": "Авганистан",
    "AM": "Јерменија",
    "AZ": "Азербејџан",
    "BH": "Бахреин",
    "BD": "Бангладеш",
    "BT": "Бутан",
    "BN": "Брунеј",
    "KH": "Камбоџа",
    "CN": "Кина",
    "CY": "Кипар",
    "GE": "Грузија",
    "IN": "Индија",
    "ID": "Индонезија",
    "IR": "Иран",
    "IQ": "Ирак",
    "IL": "Израел",
    "JP": "Јапан",
    "JO": "Јордан",
    "KZ": "Казахстан",
    "KW": "Кувајт",
    "KG": "Киргистан",
    "LA": "Лаос",
    "LB": "Либан",
    "MY": "Малезија",
    "MV": "Малдиви",
    "MN": "Монголија",
    "MM": "Мјанмар",
    "NP": "Непал",
    "KP": "Северна Кореја",
    "OM": "Оман",
    "PK": "Пакистан",
    "PH": "Филипини",
    "PS": "Палестина",
    "QA": "Катар",
    "SA": "Саудијска Арабија",
    "SG": "Сингапур",
    "KR": "Јужна Кореја",
    "LK": "Шри Ланка",
    "SY": "Сирија",
    "TW": "Тајван",
    "TJ": "Таџикистан",
    "TH": "Тајланд",
    "TL": "Источни Тимор",
    "TR": "Турска",
    "TM": "Туркменистан",
    "AE": "Уједињени Арапски Емирати",
    "UZ": "Узбекистан",
    "VN": "Вијетнам",
    "YE": "Јемен",
    # Europe
    "AL": "Албанија",
    "AD": "Андора",
    "AT": "Аустрија",
    "BY": "Белорусија",
    "BE": "Белгија",
    "BA": "Босна и Херцеговина",
    "BG": "Бугарска",
    "HR": "Хрватска",
    "CZ": "Чешка",
    "DK": "Данска",
    "EE": "Естонија",
    "FI": "Финска",
    "FR": "Француска",
    "DE": "Немачка",
    "GR": "Грчка",
    "HU": "Мађарска",
    "IS": "Исланд",
    "IE": "Ирска",
    "IT": "Италија",
    "XK": "Косово",
    "LV": "Летонија",
    "LI": "Лихтенштајн",
    "LT": "Литванија",
    "LU": "Луксембург",
    "MT": "Малта",
    "MD": "Молдавија",
    "MC": "Монако",
    "ME": "Црна Гора",
    "NL": "Холандија",
    "MK": "Северна Македонија",
    "NO": "Норвешка",
    "PL": "Пољска",
    "PT": "Португалија",
    "RO": "Румунија",
    "RU": "Русија",
    "SM": "Сан Марино",
    "RS": "Србија",
    "SK": "Словачка",
    "SI": "Словенија",
    "ES": "Шпанија",
    "SE": "Шведска",
    "CH": "Швајцарска",
    "UA": "Украјина",
    "GB": "Уједињено Краљевство",
    "VA": "Ватикан",
    # North America
    "AG": "Антигва и Барбуда",
    "BS": "Бахами",
    "BB": "Барбадос",
    "BZ": "Белизе",
    "CA": "Канада",
    "CR": "Костарика",
    "CU": "Куба",
    "DM": "Доминика",
    "DO": "Доминиканска Република",
    "SV": "Салвадор",
    "GD": "Гренада",
    "GT": "Гватемала",
    "HT": "Хаити",
    "HN": "Хондурас",
    "JM": "Јамајка",
    "MX": "Мексико",
    "NI": "Никарагва",
    "PA": "Панама",
    "KN": "Сент Китс и Невис",
    "LC": "Света Луција",
    "VC": "Свети Винсент и Гренадини",
    "TT": "Тринидад и Тобаго",
    "US": "Сједињене Америчке Државе",
    # Oceania
    "AU": "Аустралија",
    "FJ": "Фиџи",
    "KI": "Кирибати",
    "MH": "Маршалска Острва",
    "FM": "Микронезија",
    "NR": "Науру",
    "NZ": "Нови Зеланд",
    "PW": "Палау",
    "PG": "Папуа Нова Гвинеја",
    "WS": "Самоа",
    "SB": "Соломонска Острва",
    "TO": "Тонга",
    "TV": "Тувалу",
    "VU": "Вануату",
    # South America
    "AR": "Аргентина",
    "BO": "Боливија",
    "BR": "Бразил",
    "CL": "Чиле",
    "CO": "Колумбија",
    "EC": "Еквадор",
    "GY": "Гвајана",
    "PY": "Парагвај",
    "PE": "Перу",
    "SR": "Суринам",
    "UY": "Уругвај",
    "VE": "Венецуела",
}

# --- Countries: id -> Serbian (Cyrillic) capital --------------------------------------------
COUNTRY_CAPITAL_SR: dict[str, str] = {
    # Africa
    "DZ": "Алжир",
    "AO": "Луанда",
    "BJ": "Порто Ново",
    "BW": "Габороне",
    "BF": "Уагадугу",
    "BI": "Гитега",
    "CV": "Праја",
    "CM": "Јаунде",
    "CF": "Бангуи",
    "TD": "Нџамена",
    "KM": "Морони",
    "CD": "Киншаса",
    "DJ": "Џибути",
    "EG": "Каиро",
    "GQ": "Малабо",
    "ER": "Асмара",
    "SZ": "Мбабане",
    "ET": "Адис Абеба",
    "GA": "Либрвил",
    "GM": "Банжул",
    "GH": "Акра",
    "GN": "Конакри",
    "GW": "Бисао",
    "CI": "Јамусукро",
    "KE": "Најроби",
    "LS": "Масеру",
    "LR": "Монровија",
    "LY": "Триполи",
    "MG": "Антананариво",
    "MW": "Лилонгве",
    "ML": "Бамако",
    "MR": "Нуакшот",
    "MU": "Порт Луис",
    "MA": "Рабат",
    "MZ": "Мапуто",
    "NA": "Виндхук",
    "NE": "Нијамеј",
    "NG": "Абуџа",
    "CG": "Бразавил",
    "RW": "Кигали",
    "ST": "Сао Томе",
    "SN": "Дакар",
    "SC": "Викторија",
    "SL": "Фритаун",
    "SO": "Могадиш",
    "ZA": "Преторија",
    "SS": "Џуба",
    "SD": "Картум",
    "TZ": "Додома",
    "TG": "Ломе",
    "TN": "Тунис",
    "UG": "Кампала",
    "ZM": "Лусака",
    "ZW": "Хараре",
    # Asia
    "AF": "Кабул",
    "AM": "Јереван",
    "AZ": "Баку",
    "BH": "Манама",
    "BD": "Дака",
    "BT": "Тимпу",
    "BN": "Бандар Сери Бегаван",
    "KH": "Пном Пен",
    "CN": "Пекинг",
    "CY": "Никозија",
    "GE": "Тбилиси",
    "IN": "Њу Делхи",
    "ID": "Џакарта",
    "IR": "Техеран",
    "IQ": "Багдад",
    "IL": "Јерусалим",
    "JP": "Токио",
    "JO": "Аман",
    "KZ": "Астана",
    "KW": "Кувајт",
    "KG": "Бишкек",
    "LA": "Вијентијан",
    "LB": "Бејрут",
    "MY": "Куала Лумпур",
    "MV": "Мале",
    "MN": "Улан Батор",
    "MM": "Најпједо",
    "NP": "Катманду",
    "KP": "Пјонгјанг",
    "OM": "Мускат",
    "PK": "Исламабад",
    "PH": "Манила",
    "PS": "Рамала",
    "QA": "Доха",
    "SA": "Ријад",
    "SG": "Сингапур",
    "KR": "Сеул",
    "LK": "Сри Џајаварданапура Коте",
    "SY": "Дамаск",
    "TW": "Тајпеј",
    "TJ": "Душанбе",
    "TH": "Бангкок",
    "TL": "Дили",
    "TR": "Анкара",
    "TM": "Ашхабад",
    "AE": "Абу Даби",
    "UZ": "Ташкент",
    "VN": "Ханој",
    "YE": "Сана",
    # Europe
    "AL": "Тирана",
    "AD": "Андора ла Веља",
    "AT": "Беч",
    "BY": "Минск",
    "BE": "Брисел",
    "BA": "Сарајево",
    "BG": "Софија",
    "HR": "Загреб",
    "CZ": "Праг",
    "DK": "Копенхаген",
    "EE": "Талин",
    "FI": "Хелсинки",
    "FR": "Париз",
    "DE": "Берлин",
    "GR": "Атина",
    "HU": "Будимпешта",
    "IS": "Рејкјавик",
    "IE": "Даблин",
    "IT": "Рим",
    "XK": "Приштина",
    "LV": "Рига",
    "LI": "Вадуц",
    "LT": "Вилњус",
    "LU": "Луксембург",
    "MT": "Валета",
    "MD": "Кишињев",
    "MC": "Монако",
    "ME": "Подгорица",
    "NL": "Амстердам",
    "MK": "Скопље",
    "NO": "Осло",
    "PL": "Варшава",
    "PT": "Лисабон",
    "RO": "Букурешт",
    "RU": "Москва",
    "SM": "Сан Марино",
    "RS": "Београд",
    "SK": "Братислава",
    "SI": "Љубљана",
    "ES": "Мадрид",
    "SE": "Стокхолм",
    "CH": "Берн",
    "UA": "Кијев",
    "GB": "Лондон",
    "VA": "Ватикан",
    # North America
    "AG": "Сент Џонс",
    "BS": "Насау",
    "BB": "Бриџтаун",
    "BZ": "Белмопан",
    "CA": "Отава",
    "CR": "Сан Хосе",
    "CU": "Хавана",
    "DM": "Розо",
    "DO": "Санто Доминго",
    "SV": "Сан Салвадор",
    "GD": "Сент Џорџес",
    "GT": "Гватемала",
    "HT": "Порт о Пренс",
    "HN": "Тегусигалпа",
    "JM": "Кингстон",
    "MX": "Мексико Сити",
    "NI": "Манагва",
    "PA": "Панама",
    "KN": "Басетер",
    "LC": "Кастри",
    "VC": "Кингстаун",
    "TT": "Порт оф Спејн",
    "US": "Вашингтон",
    # Oceania
    "AU": "Канбера",
    "FJ": "Сува",
    "KI": "Јужна Тарава",
    "MH": "Маџуро",
    "FM": "Паликир",
    "NR": "Јарен",
    "NZ": "Велингтон",
    "PW": "Нгерулмуд",
    "PG": "Порт Морзби",
    "WS": "Апија",
    "SB": "Хонијара",
    "TO": "Нукуалофа",
    "TV": "Фунафути",
    "VU": "Порт Вила",
    # South America
    "AR": "Буенос Ајрес",
    "BO": "Сукре",
    "BR": "Бразилија",
    "CL": "Сантјаго",
    "CO": "Богота",
    "EC": "Кито",
    "GY": "Џорџтаун",
    "PY": "Асунсион",
    "PE": "Лима",
    "SR": "Парамарибо",
    "UY": "Монтевидео",
    "VE": "Каракас",
}

# --- Rivers: id -> Serbian (Cyrillic) name --------------------------------------------------
RIVER_NAME_SR: dict[str, str] = {
    "nile": "Нил",
    "amazon": "Амазон",
    "yangtze": "Јангце",
    "mississippi": "Мисисипи",
    "yenisei": "Јенисеј",
    "yellow-river": "Жута река",
    "ob": "Об",
    "congo": "Конго",
    "lena": "Лена",
    "niger": "Нигер",
    "mekong": "Меконг",
    "missouri": "Мисури",
    "volga": "Волга",
    "zambezi": "Замбези",
    "ganges": "Ганг",
    "indus": "Инд",
    "murray": "Мари",
    "euphrates": "Еуфрат",
    "tigris": "Тигар",
    "rhine": "Рајна",
    "danube": "Дунав",
    "colorado": "Колорадо",
    "columbia": "Колумбија",
    "irrawaddy": "Иравади",
    "orange": "Оранж",
    "parana": "Парана",
    "amur": "Амур",
    "dnieper": "Дњепар",
    "senegal-river": "Сенегал",
    "orinoco": "Ориноко",
    "sao-francisco": "Сан Франсиско",
    "tocantins": "Токантинс",
}

# --- Mountains: id -> Serbian (Cyrillic) name -----------------------------------------------
MOUNTAIN_NAME_SR: dict[str, str] = {
    "himalayas": "Хималаји",
    "andes": "Анди",
    "rockies": "Стеновите планине",
    "alps": "Алпи",
    "great-dividing-range": "Велики разводни венац",
    "kunlun": "Куенлун",
    "tian-shan": "Тјеншан",
    "altai": "Алтај",
    "caucasus": "Кавказ",
    "pyrenees": "Пиринеји",
    "carpathians": "Карпати",
    "appalachians": "Апалачи",
    "atlas": "Атлас",
    "drakensberg": "Драконове планине",
    "ethiopian-highlands": "Етиопска висораван",
    "scandinavian-mountains": "Скандинавске планине",
    "hindu-kush": "Хиндукуш",
    "karakoram": "Каракорум",
    "pamir": "Памир",
    "sierra-nevada-us": "Сијера Невада",
    "southern-alps": "Јужни Алпи",
    "zagros": "Загрос",
    "eastern-rift-highlands": "Висораван Источног раседа",
}

# --- Seas: id -> Serbian (Cyrillic) name ----------------------------------------------------
SEA_NAME_SR: dict[str, str] = {
    "pacific": "Тихи океан",
    "atlantic": "Атлантски океан",
    "indian": "Индијски океан",
    "southern": "Јужни океан",
    "arctic": "Северни ледени океан",
    "mediterranean": "Средоземно море",
    "caribbean": "Карипско море",
    "south-china": "Јужнокинеско море",
    "bering": "Берингово море",
    "gulf-of-mexico": "Мексички залив",
    "north-sea": "Северно море",
    "red-sea": "Црвено море",
    "black-sea": "Црно море",
    "caspian-sea": "Каспијско језеро",
    "persian-gulf": "Персијски залив",
    "east-china": "Источнокинеско море",
    "bay-of-bengal": "Бенгалски залив",
    "arabian-sea": "Арабијско море",
    "coral-sea": "Коралско море",
    "tasman-sea": "Тасманово море",
}


def _insert_after(obj: dict, anchor: str, key: str, value) -> OrderedDict:
    """Return an OrderedDict copy of obj with key/value inserted right after anchor."""
    out: OrderedDict = OrderedDict()
    for k, v in obj.items():
        if k == key:
            continue  # drop any pre-existing sr column so we re-seed cleanly
        out[k] = v
        if k == anchor:
            out[key] = value
    if anchor not in obj:  # anchor missing: append at end
        out[key] = value
    return out


def _seed(filename: str, names: dict[str, str], capitals: dict[str, str] | None) -> None:
    path = RESOURCES / filename
    data = json.loads(path.read_text(encoding="utf-8"))
    missing: list[str] = []
    seeded = []
    for entry in data:
        eid = entry["id"]
        name = names.get(eid)
        if name is None:
            missing.append(eid)
            seeded.append(entry)
            continue
        new_entry = _insert_after(entry, "name_nl", "name_sr", name)
        if capitals is not None:
            cap = capitals.get(eid)
            if cap is None:
                missing.append(f"{eid}(capital)")
            else:
                new_entry = _insert_after(new_entry, "capital_nl", "capital_sr", cap)
        seeded.append(new_entry)
    if missing:
        print(f"FAIL: {filename} missing Serbian for: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)
    path.write_text(json.dumps(seeded, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"seeded sr into {filename} ({len(seeded)} entries)")


def main() -> None:
    _seed("countries.json", COUNTRY_NAME_SR, COUNTRY_CAPITAL_SR)
    _seed("rivers.json", RIVER_NAME_SR, None)
    _seed("mountains.json", MOUNTAIN_NAME_SR, None)
    _seed("seas.json", SEA_NAME_SR, None)


if __name__ == "__main__":
    main()
