#!/usr/bin/env python3
"""One-off (idempotent): seed Polish geo columns into the bundled geo JSON.

Adds ``name_pl`` (and ``capital_pl`` for countries) to EVERY entity in
``countries.json``/``rivers.json``/``mountains.json``/``seas.json`` — Polish is a
COMPLETE-content language, so coverage is total (zero gaps; the pl -> en fallback is a
never-hit safety net).

Translations use established Polish exonyms where they exist (Niemcy, Hiszpania, Włochy,
Chiny, Francja, Rosja, Moskwa, Londyn, Pekin, Morze Śródziemne, Alpy, Pireneje, Dunaj, Ren,
…) and keep the local/native name where Polish has no distinct exonym. The maps below are
keyed by the entity id, so the values are explicit and reviewable.

Idempotent: re-running rewrites the pl columns from the same source maps. The ``name_pl`` key
is inserted immediately after ``name_it`` (and ``capital_pl`` after ``capital_it``) so the
JSON stays readable and the pl columns sit adjacent to the other per-language columns.

Usage:
    python3 scripts/seed-pl-geo.py
"""

from __future__ import annotations

import json
import sys
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCES = REPO_ROOT / "Hanahuac" / "Resources"

# --- Countries: id -> Polish name -----------------------------------------------------------
COUNTRY_NAME_PL: dict[str, str] = {
    # Africa
    "DZ": "Algieria",
    "AO": "Angola",
    "BJ": "Benin",
    "BW": "Botswana",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Republika Zielonego Przylądka",
    "CM": "Kamerun",
    "CF": "Republika Środkowoafrykańska",
    "TD": "Czad",
    "KM": "Komory",
    "CD": "Demokratyczna Republika Konga",
    "DJ": "Dżibuti",
    "EG": "Egipt",
    "GQ": "Gwinea Równikowa",
    "ER": "Erytrea",
    "SZ": "Eswatini",
    "ET": "Etiopia",
    "GA": "Gabon",
    "GM": "Gambia",
    "GH": "Ghana",
    "GN": "Gwinea",
    "GW": "Gwinea Bissau",
    "CI": "Wybrzeże Kości Słoniowej",
    "KE": "Kenia",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libia",
    "MG": "Madagaskar",
    "MW": "Malawi",
    "ML": "Mali",
    "MR": "Mauretania",
    "MU": "Mauritius",
    "MA": "Maroko",
    "MZ": "Mozambik",
    "NA": "Namibia",
    "NE": "Niger",
    "NG": "Nigeria",
    "CG": "Republika Konga",
    "RW": "Rwanda",
    "ST": "Wyspy Świętego Tomasza i Książęca",
    "SN": "Senegal",
    "SC": "Seszele",
    "SL": "Sierra Leone",
    "SO": "Somalia",
    "ZA": "Republika Południowej Afryki",
    "SS": "Sudan Południowy",
    "SD": "Sudan",
    "TZ": "Tanzania",
    "TG": "Togo",
    "TN": "Tunezja",
    "UG": "Uganda",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    # Asia
    "AF": "Afganistan",
    "AM": "Armenia",
    "AZ": "Azerbejdżan",
    "BH": "Bahrajn",
    "BD": "Bangladesz",
    "BT": "Bhutan",
    "BN": "Brunei",
    "KH": "Kambodża",
    "CN": "Chiny",
    "CY": "Cypr",
    "GE": "Gruzja",
    "IN": "Indie",
    "ID": "Indonezja",
    "IR": "Iran",
    "IQ": "Irak",
    "IL": "Izrael",
    "JP": "Japonia",
    "JO": "Jordania",
    "KZ": "Kazachstan",
    "KW": "Kuwejt",
    "KG": "Kirgistan",
    "LA": "Laos",
    "LB": "Liban",
    "MY": "Malezja",
    "MV": "Malediwy",
    "MN": "Mongolia",
    "MM": "Mjanma",
    "NP": "Nepal",
    "KP": "Korea Północna",
    "OM": "Oman",
    "PK": "Pakistan",
    "PH": "Filipiny",
    "PS": "Palestyna",
    "QA": "Katar",
    "SA": "Arabia Saudyjska",
    "SG": "Singapur",
    "KR": "Korea Południowa",
    "LK": "Sri Lanka",
    "SY": "Syria",
    "TW": "Tajwan",
    "TJ": "Tadżykistan",
    "TH": "Tajlandia",
    "TL": "Timor Wschodni",
    "TR": "Turcja",
    "TM": "Turkmenistan",
    "AE": "Zjednoczone Emiraty Arabskie",
    "UZ": "Uzbekistan",
    "VN": "Wietnam",
    "YE": "Jemen",
    # Europe
    "AL": "Albania",
    "AD": "Andora",
    "AT": "Austria",
    "BY": "Białoruś",
    "BE": "Belgia",
    "BA": "Bośnia i Hercegowina",
    "BG": "Bułgaria",
    "HR": "Chorwacja",
    "CZ": "Czechy",
    "DK": "Dania",
    "EE": "Estonia",
    "FI": "Finlandia",
    "FR": "Francja",
    "DE": "Niemcy",
    "GR": "Grecja",
    "HU": "Węgry",
    "IS": "Islandia",
    "IE": "Irlandia",
    "IT": "Włochy",
    "XK": "Kosowo",
    "LV": "Łotwa",
    "LI": "Liechtenstein",
    "LT": "Litwa",
    "LU": "Luksemburg",
    "MT": "Malta",
    "MD": "Mołdawia",
    "MC": "Monako",
    "ME": "Czarnogóra",
    "NL": "Holandia",
    "MK": "Macedonia Północna",
    "NO": "Norwegia",
    "PL": "Polska",
    "PT": "Portugalia",
    "RO": "Rumunia",
    "RU": "Rosja",
    "SM": "San Marino",
    "RS": "Serbia",
    "SK": "Słowacja",
    "SI": "Słowenia",
    "ES": "Hiszpania",
    "SE": "Szwecja",
    "CH": "Szwajcaria",
    "UA": "Ukraina",
    "GB": "Wielka Brytania",
    "VA": "Watykan",
    # North America
    "AG": "Antigua i Barbuda",
    "BS": "Bahamy",
    "BB": "Barbados",
    "BZ": "Belize",
    "CA": "Kanada",
    "CR": "Kostaryka",
    "CU": "Kuba",
    "DM": "Dominika",
    "DO": "Dominikana",
    "SV": "Salwador",
    "GD": "Grenada",
    "GT": "Gwatemala",
    "HT": "Haiti",
    "HN": "Honduras",
    "JM": "Jamajka",
    "MX": "Meksyk",
    "NI": "Nikaragua",
    "PA": "Panama",
    "KN": "Saint Kitts i Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent i Grenadyny",
    "TT": "Trynidad i Tobago",
    "US": "Stany Zjednoczone",
    # Oceania
    "AU": "Australia",
    "FJ": "Fidżi",
    "KI": "Kiribati",
    "MH": "Wyspy Marshalla",
    "FM": "Mikronezja",
    "NR": "Nauru",
    "NZ": "Nowa Zelandia",
    "PW": "Palau",
    "PG": "Papua-Nowa Gwinea",
    "WS": "Samoa",
    "SB": "Wyspy Salomona",
    "TO": "Tonga",
    "TV": "Tuvalu",
    "VU": "Vanuatu",
    # South America
    "AR": "Argentyna",
    "BO": "Boliwia",
    "BR": "Brazylia",
    "CL": "Chile",
    "CO": "Kolumbia",
    "EC": "Ekwador",
    "GY": "Gujana",
    "PY": "Paragwaj",
    "PE": "Peru",
    "SR": "Surinam",
    "UY": "Urugwaj",
    "VE": "Wenezuela",
}

# --- Countries: id -> Polish capital --------------------------------------------------------
COUNTRY_CAPITAL_PL: dict[str, str] = {
    # Africa
    "DZ": "Algier",
    "AO": "Luanda",
    "BJ": "Porto-Novo",
    "BW": "Gaborone",
    "BF": "Wagadugu",
    "BI": "Gitega",
    "CV": "Praia",
    "CM": "Jaunde",
    "CF": "Bangi",
    "TD": "Ndżamena",
    "KM": "Moroni",
    "CD": "Kinszasa",
    "DJ": "Dżibuti",
    "EG": "Kair",
    "GQ": "Malabo",
    "ER": "Asmara",
    "SZ": "Mbabane",
    "ET": "Addis Abeba",
    "GA": "Libreville",
    "GM": "Bandżul",
    "GH": "Akra",
    "GN": "Konakry",
    "GW": "Bissau",
    "CI": "Jamusukro",
    "KE": "Nairobi",
    "LS": "Maseru",
    "LR": "Monrowia",
    "LY": "Trypolis",
    "MG": "Antananarywa",
    "MW": "Lilongwe",
    "ML": "Bamako",
    "MR": "Nawakszut",
    "MU": "Port Louis",
    "MA": "Rabat",
    "MZ": "Maputo",
    "NA": "Windhuk",
    "NE": "Niamey",
    "NG": "Abudża",
    "CG": "Brazzaville",
    "RW": "Kigali",
    "ST": "São Tomé",
    "SN": "Dakar",
    "SC": "Victoria",
    "SL": "Freetown",
    "SO": "Mogadiszu",
    "ZA": "Pretoria",
    "SS": "Dżuba",
    "SD": "Chartum",
    "TZ": "Dodoma",
    "TG": "Lomé",
    "TN": "Tunis",
    "UG": "Kampala",
    "ZM": "Lusaka",
    "ZW": "Harare",
    # Asia
    "AF": "Kabul",
    "AM": "Erywań",
    "AZ": "Baku",
    "BH": "Manama",
    "BD": "Dhaka",
    "BT": "Thimphu",
    "BN": "Bandar Seri Begawan",
    "KH": "Phnom Penh",
    "CN": "Pekin",
    "CY": "Nikozja",
    "GE": "Tbilisi",
    "IN": "Nowe Delhi",
    "ID": "Dżakarta",
    "IR": "Teheran",
    "IQ": "Bagdad",
    "IL": "Jerozolima",
    "JP": "Tokio",
    "JO": "Amman",
    "KZ": "Astana",
    "KW": "Kuwejt",
    "KG": "Biszkek",
    "LA": "Wientian",
    "LB": "Bejrut",
    "MY": "Kuala Lumpur",
    "MV": "Male",
    "MN": "Ułan Bator",
    "MM": "Naypyidaw",
    "NP": "Katmandu",
    "KP": "Pjongjang",
    "OM": "Maskat",
    "PK": "Islamabad",
    "PH": "Manila",
    "PS": "Ramallah",
    "QA": "Ad-Dauha",
    "SA": "Rijad",
    "SG": "Singapur",
    "KR": "Seul",
    "LK": "Sri Dżajawardenepura Kotte",
    "SY": "Damaszek",
    "TW": "Tajpej",
    "TJ": "Duszanbe",
    "TH": "Bangkok",
    "TL": "Dili",
    "TR": "Ankara",
    "TM": "Aszchabad",
    "AE": "Abu Zabi",
    "UZ": "Taszkent",
    "VN": "Hanoi",
    "YE": "Sana",
    # Europe
    "AL": "Tirana",
    "AD": "Andora",
    "AT": "Wiedeń",
    "BY": "Mińsk",
    "BE": "Bruksela",
    "BA": "Sarajewo",
    "BG": "Sofia",
    "HR": "Zagrzeb",
    "CZ": "Praga",
    "DK": "Kopenhaga",
    "EE": "Tallinn",
    "FI": "Helsinki",
    "FR": "Paryż",
    "DE": "Berlin",
    "GR": "Ateny",
    "HU": "Budapeszt",
    "IS": "Reykjavík",
    "IE": "Dublin",
    "IT": "Rzym",
    "XK": "Prisztina",
    "LV": "Ryga",
    "LI": "Vaduz",
    "LT": "Wilno",
    "LU": "Luksemburg",
    "MT": "Valletta",
    "MD": "Kiszyniów",
    "MC": "Monako",
    "ME": "Podgorica",
    "NL": "Amsterdam",
    "MK": "Skopje",
    "NO": "Oslo",
    "PL": "Warszawa",
    "PT": "Lizbona",
    "RO": "Bukareszt",
    "RU": "Moskwa",
    "SM": "San Marino",
    "RS": "Belgrad",
    "SK": "Bratysława",
    "SI": "Lublana",
    "ES": "Madryt",
    "SE": "Sztokholm",
    "CH": "Berno",
    "UA": "Kijów",
    "GB": "Londyn",
    "VA": "Watykan",
    # North America
    "AG": "Saint John's",
    "BS": "Nassau",
    "BB": "Bridgetown",
    "BZ": "Belmopan",
    "CA": "Ottawa",
    "CR": "San José",
    "CU": "Hawana",
    "DM": "Roseau",
    "DO": "Santo Domingo",
    "SV": "San Salvador",
    "GD": "Saint George's",
    "GT": "Gwatemala",
    "HT": "Port-au-Prince",
    "HN": "Tegucigalpa",
    "JM": "Kingston",
    "MX": "Meksyk",
    "NI": "Managua",
    "PA": "Panama",
    "KN": "Basseterre",
    "LC": "Castries",
    "VC": "Kingstown",
    "TT": "Port-of-Spain",
    "US": "Waszyngton",
    # Oceania
    "AU": "Canberra",
    "FJ": "Suva",
    "KI": "Tarawa Południowa",
    "MH": "Majuro",
    "FM": "Palikir",
    "NR": "Yaren",
    "NZ": "Wellington",
    "PW": "Ngerulmud",
    "PG": "Port Moresby",
    "WS": "Apia",
    "SB": "Honiara",
    "TO": "Nuku'alofa",
    "TV": "Funafuti",
    "VU": "Port Vila",
    # South America
    "AR": "Buenos Aires",
    "BO": "Sucre",
    "BR": "Brasília",
    "CL": "Santiago",
    "CO": "Bogota",
    "EC": "Quito",
    "GY": "Georgetown",
    "PY": "Asunción",
    "PE": "Lima",
    "SR": "Paramaribo",
    "UY": "Montevideo",
    "VE": "Caracas",
}

# --- Rivers: id -> Polish name --------------------------------------------------------------
RIVER_NAME_PL: dict[str, str] = {
    "nile": "Nil",
    "amazon": "Amazonka",
    "yangtze": "Jangcy",
    "mississippi": "Missisipi",
    "yenisei": "Jenisej",
    "yellow-river": "Rzeka Żółta",
    "ob": "Ob",
    "congo": "Kongo",
    "lena": "Lena",
    "niger": "Niger",
    "mekong": "Mekong",
    "missouri": "Missouri",
    "volga": "Wołga",
    "zambezi": "Zambezi",
    "ganges": "Ganges",
    "indus": "Indus",
    "murray": "Murray",
    "euphrates": "Eufrat",
    "tigris": "Tygrys",
    "rhine": "Ren",
    "danube": "Dunaj",
    "colorado": "Kolorado",
    "columbia": "Kolumbia",
    "irrawaddy": "Irawadi",
    "orange": "Oranje",
    "parana": "Parana",
    "amur": "Amur",
    "dnieper": "Dniepr",
    "senegal-river": "Senegal",
    "orinoco": "Orinoko",
    "sao-francisco": "São Francisco",
    "tocantins": "Tocantins",
}

# --- Mountains: id -> Polish name -----------------------------------------------------------
MOUNTAIN_NAME_PL: dict[str, str] = {
    "himalayas": "Himalaje",
    "andes": "Andy",
    "rockies": "Góry Skaliste",
    "alps": "Alpy",
    "great-dividing-range": "Wielkie Góry Wododziałowe",
    "kunlun": "Kunlun",
    "tian-shan": "Tienszan",
    "altai": "Ałtaj",
    "caucasus": "Kaukaz",
    "pyrenees": "Pireneje",
    "carpathians": "Karpaty",
    "appalachians": "Appalachy",
    "atlas": "Atlas",
    "drakensberg": "Góry Smocze",
    "ethiopian-highlands": "Wyżyna Abisyńska",
    "scandinavian-mountains": "Góry Skandynawskie",
    "hindu-kush": "Hindukusz",
    "karakoram": "Karakorum",
    "pamir": "Pamir",
    "sierra-nevada-us": "Sierra Nevada",
    "southern-alps": "Alpy Południowe",
    "zagros": "Zagros",
    "eastern-rift-highlands": "Wyżyny Wielkiego Rowu Wschodnioafrykańskiego",
}

# --- Seas: id -> Polish name ----------------------------------------------------------------
SEA_NAME_PL: dict[str, str] = {
    "pacific": "Ocean Spokojny",
    "atlantic": "Ocean Atlantycki",
    "indian": "Ocean Indyjski",
    "southern": "Ocean Południowy",
    "arctic": "Ocean Arktyczny",
    "mediterranean": "Morze Śródziemne",
    "caribbean": "Morze Karaibskie",
    "south-china": "Morze Południowochińskie",
    "bering": "Morze Beringa",
    "gulf-of-mexico": "Zatoka Meksykańska",
    "north-sea": "Morze Północne",
    "red-sea": "Morze Czerwone",
    "black-sea": "Morze Czarne",
    "caspian-sea": "Morze Kaspijskie",
    "persian-gulf": "Zatoka Perska",
    "east-china": "Morze Wschodniochińskie",
    "bay-of-bengal": "Zatoka Bengalska",
    "arabian-sea": "Morze Arabskie",
    "coral-sea": "Morze Koralowe",
    "tasman-sea": "Morze Tasmana",
}


def _insert_after(obj: dict, anchor: str, key: str, value) -> OrderedDict:
    """Return an OrderedDict copy of obj with key/value inserted right after anchor."""
    out: OrderedDict = OrderedDict()
    for k, v in obj.items():
        if k == key:
            continue  # drop any pre-existing pl column so we re-seed cleanly
        out[k] = v
        if k == anchor:
            out[key] = value
    if anchor not in obj:  # anchor missing: append at end
        out[key] = value
    return out


def _seed(filename: str, names: dict[str, str], capitals: dict[str, str] | None) -> None:
    path = RESOURCES / filename
    data = json.loads(path.read_text(encoding="utf-8"))
    missing: list[str] = []
    seeded = []
    for entry in data:
        eid = entry["id"]
        name = names.get(eid)
        if name is None:
            missing.append(eid)
            seeded.append(entry)
            continue
        new_entry = _insert_after(entry, "name_it", "name_pl", name)
        if capitals is not None:
            cap = capitals.get(eid)
            if cap is None:
                missing.append(f"{eid}(capital)")
            else:
                new_entry = _insert_after(new_entry, "capital_it", "capital_pl", cap)
        seeded.append(new_entry)
    if missing:
        print(f"FAIL: {filename} missing Polish for: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)
    path.write_text(json.dumps(seeded, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"seeded pl into {filename} ({len(seeded)} entries)")


def main() -> None:
    _seed("countries.json", COUNTRY_NAME_PL, COUNTRY_CAPITAL_PL)
    _seed("rivers.json", RIVER_NAME_PL, None)
    _seed("mountains.json", MOUNTAIN_NAME_PL, None)
    _seed("seas.json", SEA_NAME_PL, None)


if __name__ == "__main__":
    main()
