#!/usr/bin/env python3
"""Durable (idempotent): seed Dutch geo columns into the bundled geo JSON.

Adds ``name_nl`` (and ``capital_nl`` for countries) to EVERY entity in
``countries.json``/``rivers.json``/``mountains.json``/``seas.json`` — Dutch is a
COMPLETE-content language, so coverage is total (zero gaps; the nl -> en fallback is a
never-hit safety net).

Translations use established Dutch exonyms where they exist (Duitsland, Spanje, Italië,
Frankrijk, China, Rusland, Moskou, Londen, Peking, Middellandse Zee, Alpen, Pyreneeën,
Donau, Rijn, …) and keep the local/native name where Dutch has no distinct exonym. The maps
below are keyed by the entity id, so the values are explicit and reviewable.

Idempotent: re-running rewrites the nl columns from the same source maps. The ``name_nl`` key
is inserted immediately after ``name_pl`` (and ``capital_nl`` after ``capital_pl``) so the
JSON stays readable and the nl columns sit adjacent to the other per-language columns.

Usage:
    python3 scripts/seed-nl-geo.py
"""

from __future__ import annotations

import json
import sys
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCES = REPO_ROOT / "Hanahuac" / "Resources"

# --- Countries: id -> Dutch name ------------------------------------------------------------
COUNTRY_NAME_NL: dict[str, str] = {
    # Africa
    "DZ": "Algerije",
    "AO": "Angola",
    "BJ": "Benin",
    "BW": "Botswana",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Kaapverdië",
    "CM": "Kameroen",
    "CF": "Centraal-Afrikaanse Republiek",
    "TD": "Tsjaad",
    "KM": "Comoren",
    "CD": "Democratische Republiek Congo",
    "DJ": "Djibouti",
    "EG": "Egypte",
    "GQ": "Equatoriaal-Guinea",
    "ER": "Eritrea",
    "SZ": "Eswatini",
    "ET": "Ethiopië",
    "GA": "Gabon",
    "GM": "Gambia",
    "GH": "Ghana",
    "GN": "Guinee",
    "GW": "Guinee-Bissau",
    "CI": "Ivoorkust",
    "KE": "Kenia",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libië",
    "MG": "Madagaskar",
    "MW": "Malawi",
    "ML": "Mali",
    "MR": "Mauritanië",
    "MU": "Mauritius",
    "MA": "Marokko",
    "MZ": "Mozambique",
    "NA": "Namibië",
    "NE": "Niger",
    "NG": "Nigeria",
    "CG": "Congo-Brazzaville",
    "RW": "Rwanda",
    "ST": "Sao Tomé en Principe",
    "SN": "Senegal",
    "SC": "Seychellen",
    "SL": "Sierra Leone",
    "SO": "Somalië",
    "ZA": "Zuid-Afrika",
    "SS": "Zuid-Soedan",
    "SD": "Soedan",
    "TZ": "Tanzania",
    "TG": "Togo",
    "TN": "Tunesië",
    "UG": "Oeganda",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    # Asia
    "AF": "Afghanistan",
    "AM": "Armenië",
    "AZ": "Azerbeidzjan",
    "BH": "Bahrein",
    "BD": "Bangladesh",
    "BT": "Bhutan",
    "BN": "Brunei",
    "KH": "Cambodja",
    "CN": "China",
    "CY": "Cyprus",
    "GE": "Georgië",
    "IN": "India",
    "ID": "Indonesië",
    "IR": "Iran",
    "IQ": "Irak",
    "IL": "Israël",
    "JP": "Japan",
    "JO": "Jordanië",
    "KZ": "Kazachstan",
    "KW": "Koeweit",
    "KG": "Kirgizië",
    "LA": "Laos",
    "LB": "Libanon",
    "MY": "Maleisië",
    "MV": "Maldiven",
    "MN": "Mongolië",
    "MM": "Myanmar",
    "NP": "Nepal",
    "KP": "Noord-Korea",
    "OM": "Oman",
    "PK": "Pakistan",
    "PH": "Filipijnen",
    "PS": "Palestina",
    "QA": "Qatar",
    "SA": "Saoedi-Arabië",
    "SG": "Singapore",
    "KR": "Zuid-Korea",
    "LK": "Sri Lanka",
    "SY": "Syrië",
    "TW": "Taiwan",
    "TJ": "Tadzjikistan",
    "TH": "Thailand",
    "TL": "Oost-Timor",
    "TR": "Turkije",
    "TM": "Turkmenistan",
    "AE": "Verenigde Arabische Emiraten",
    "UZ": "Oezbekistan",
    "VN": "Vietnam",
    "YE": "Jemen",
    # Europe
    "AL": "Albanië",
    "AD": "Andorra",
    "AT": "Oostenrijk",
    "BY": "Belarus",
    "BE": "België",
    "BA": "Bosnië en Herzegovina",
    "BG": "Bulgarije",
    "HR": "Kroatië",
    "CZ": "Tsjechië",
    "DK": "Denemarken",
    "EE": "Estland",
    "FI": "Finland",
    "FR": "Frankrijk",
    "DE": "Duitsland",
    "GR": "Griekenland",
    "HU": "Hongarije",
    "IS": "IJsland",
    "IE": "Ierland",
    "IT": "Italië",
    "XK": "Kosovo",
    "LV": "Letland",
    "LI": "Liechtenstein",
    "LT": "Litouwen",
    "LU": "Luxemburg",
    "MT": "Malta",
    "MD": "Moldavië",
    "MC": "Monaco",
    "ME": "Montenegro",
    "NL": "Nederland",
    "MK": "Noord-Macedonië",
    "NO": "Noorwegen",
    "PL": "Polen",
    "PT": "Portugal",
    "RO": "Roemenië",
    "RU": "Rusland",
    "SM": "San Marino",
    "RS": "Servië",
    "SK": "Slowakije",
    "SI": "Slovenië",
    "ES": "Spanje",
    "SE": "Zweden",
    "CH": "Zwitserland",
    "UA": "Oekraïne",
    "GB": "Verenigd Koninkrijk",
    "VA": "Vaticaanstad",
    # North America
    "AG": "Antigua en Barbuda",
    "BS": "Bahama's",
    "BB": "Barbados",
    "BZ": "Belize",
    "CA": "Canada",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "DM": "Dominica",
    "DO": "Dominicaanse Republiek",
    "SV": "El Salvador",
    "GD": "Grenada",
    "GT": "Guatemala",
    "HT": "Haïti",
    "HN": "Honduras",
    "JM": "Jamaica",
    "MX": "Mexico",
    "NI": "Nicaragua",
    "PA": "Panama",
    "KN": "Saint Kitts en Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent en de Grenadines",
    "TT": "Trinidad en Tobago",
    "US": "Verenigde Staten",
    # Oceania
    "AU": "Australië",
    "FJ": "Fiji",
    "KI": "Kiribati",
    "MH": "Marshalleilanden",
    "FM": "Micronesia",
    "NR": "Nauru",
    "NZ": "Nieuw-Zeeland",
    "PW": "Palau",
    "PG": "Papoea-Nieuw-Guinea",
    "WS": "Samoa",
    "SB": "Salomonseilanden",
    "TO": "Tonga",
    "TV": "Tuvalu",
    "VU": "Vanuatu",
    # South America
    "AR": "Argentinië",
    "BO": "Bolivia",
    "BR": "Brazilië",
    "CL": "Chili",
    "CO": "Colombia",
    "EC": "Ecuador",
    "GY": "Guyana",
    "PY": "Paraguay",
    "PE": "Peru",
    "SR": "Suriname",
    "UY": "Uruguay",
    "VE": "Venezuela",
}

# --- Countries: id -> Dutch capital ---------------------------------------------------------
COUNTRY_CAPITAL_NL: dict[str, str] = {
    # Africa
    "DZ": "Algiers",
    "AO": "Luanda",
    "BJ": "Porto-Novo",
    "BW": "Gaborone",
    "BF": "Ouagadougou",
    "BI": "Gitega",
    "CV": "Praia",
    "CM": "Yaoundé",
    "CF": "Bangui",
    "TD": "N'Djamena",
    "KM": "Moroni",
    "CD": "Kinshasa",
    "DJ": "Djibouti",
    "EG": "Caïro",
    "GQ": "Malabo",
    "ER": "Asmara",
    "SZ": "Mbabane",
    "ET": "Addis Abeba",
    "GA": "Libreville",
    "GM": "Banjul",
    "GH": "Accra",
    "GN": "Conakry",
    "GW": "Bissau",
    "CI": "Yamoussoukro",
    "KE": "Nairobi",
    "LS": "Maseru",
    "LR": "Monrovia",
    "LY": "Tripoli",
    "MG": "Antananarivo",
    "MW": "Lilongwe",
    "ML": "Bamako",
    "MR": "Nouakchott",
    "MU": "Port Louis",
    "MA": "Rabat",
    "MZ": "Maputo",
    "NA": "Windhoek",
    "NE": "Niamey",
    "NG": "Abuja",
    "CG": "Brazzaville",
    "RW": "Kigali",
    "ST": "Sao Tomé",
    "SN": "Dakar",
    "SC": "Victoria",
    "SL": "Freetown",
    "SO": "Mogadishu",
    "ZA": "Pretoria",
    "SS": "Juba",
    "SD": "Khartoem",
    "TZ": "Dodoma",
    "TG": "Lomé",
    "TN": "Tunis",
    "UG": "Kampala",
    "ZM": "Lusaka",
    "ZW": "Harare",
    # Asia
    "AF": "Kaboel",
    "AM": "Jerevan",
    "AZ": "Bakoe",
    "BH": "Manama",
    "BD": "Dhaka",
    "BT": "Thimphu",
    "BN": "Bandar Seri Begawan",
    "KH": "Phnom Penh",
    "CN": "Peking",
    "CY": "Nicosia",
    "GE": "Tbilisi",
    "IN": "New Delhi",
    "ID": "Jakarta",
    "IR": "Teheran",
    "IQ": "Bagdad",
    "IL": "Jeruzalem",
    "JP": "Tokio",
    "JO": "Amman",
    "KZ": "Astana",
    "KW": "Koeweit",
    "KG": "Bisjkek",
    "LA": "Vientiane",
    "LB": "Beiroet",
    "MY": "Kuala Lumpur",
    "MV": "Malé",
    "MN": "Ulaanbaatar",
    "MM": "Naypyidaw",
    "NP": "Kathmandu",
    "KP": "Pyongyang",
    "OM": "Masqat",
    "PK": "Islamabad",
    "PH": "Manilla",
    "PS": "Ramallah",
    "QA": "Doha",
    "SA": "Riyad",
    "SG": "Singapore",
    "KR": "Seoul",
    "LK": "Sri Jayawardenepura Kotte",
    "SY": "Damascus",
    "TW": "Taipei",
    "TJ": "Doesjanbe",
    "TH": "Bangkok",
    "TL": "Dili",
    "TR": "Ankara",
    "TM": "Asjchabad",
    "AE": "Abu Dhabi",
    "UZ": "Tasjkent",
    "VN": "Hanoi",
    "YE": "Sanaa",
    # Europe
    "AL": "Tirana",
    "AD": "Andorra la Vella",
    "AT": "Wenen",
    "BY": "Minsk",
    "BE": "Brussel",
    "BA": "Sarajevo",
    "BG": "Sofia",
    "HR": "Zagreb",
    "CZ": "Praag",
    "DK": "Kopenhagen",
    "EE": "Tallinn",
    "FI": "Helsinki",
    "FR": "Parijs",
    "DE": "Berlijn",
    "GR": "Athene",
    "HU": "Boedapest",
    "IS": "Reykjavik",
    "IE": "Dublin",
    "IT": "Rome",
    "XK": "Pristina",
    "LV": "Riga",
    "LI": "Vaduz",
    "LT": "Vilnius",
    "LU": "Luxemburg",
    "MT": "Valletta",
    "MD": "Chisinau",
    "MC": "Monaco",
    "ME": "Podgorica",
    "NL": "Amsterdam",
    "MK": "Skopje",
    "NO": "Oslo",
    "PL": "Warschau",
    "PT": "Lissabon",
    "RO": "Boekarest",
    "RU": "Moskou",
    "SM": "San Marino",
    "RS": "Belgrado",
    "SK": "Bratislava",
    "SI": "Ljubljana",
    "ES": "Madrid",
    "SE": "Stockholm",
    "CH": "Bern",
    "UA": "Kiev",
    "GB": "Londen",
    "VA": "Vaticaanstad",
    # North America
    "AG": "Saint John's",
    "BS": "Nassau",
    "BB": "Bridgetown",
    "BZ": "Belmopan",
    "CA": "Ottawa",
    "CR": "San José",
    "CU": "Havana",
    "DM": "Roseau",
    "DO": "Santo Domingo",
    "SV": "San Salvador",
    "GD": "Saint George's",
    "GT": "Guatemala-Stad",
    "HT": "Port-au-Prince",
    "HN": "Tegucigalpa",
    "JM": "Kingston",
    "MX": "Mexico-Stad",
    "NI": "Managua",
    "PA": "Panama-Stad",
    "KN": "Basseterre",
    "LC": "Castries",
    "VC": "Kingstown",
    "TT": "Port of Spain",
    "US": "Washington D.C.",
    # Oceania
    "AU": "Canberra",
    "FJ": "Suva",
    "KI": "Zuid-Tarawa",
    "MH": "Majuro",
    "FM": "Palikir",
    "NR": "Yaren",
    "NZ": "Wellington",
    "PW": "Ngerulmud",
    "PG": "Port Moresby",
    "WS": "Apia",
    "SB": "Honiara",
    "TO": "Nuku'alofa",
    "TV": "Funafuti",
    "VU": "Port Vila",
    # South America
    "AR": "Buenos Aires",
    "BO": "Sucre",
    "BR": "Brasília",
    "CL": "Santiago",
    "CO": "Bogota",
    "EC": "Quito",
    "GY": "Georgetown",
    "PY": "Asunción",
    "PE": "Lima",
    "SR": "Paramaribo",
    "UY": "Montevideo",
    "VE": "Caracas",
}

# --- Rivers: id -> Dutch name ---------------------------------------------------------------
RIVER_NAME_NL: dict[str, str] = {
    "nile": "Nijl",
    "amazon": "Amazone",
    "yangtze": "Jangtsekiang",
    "mississippi": "Mississippi",
    "yenisei": "Jenisej",
    "yellow-river": "Gele Rivier",
    "ob": "Ob",
    "congo": "Congo",
    "lena": "Lena",
    "niger": "Niger",
    "mekong": "Mekong",
    "missouri": "Missouri",
    "volga": "Wolga",
    "zambezi": "Zambezi",
    "ganges": "Ganges",
    "indus": "Indus",
    "murray": "Murray",
    "euphrates": "Eufraat",
    "tigris": "Tigris",
    "rhine": "Rijn",
    "danube": "Donau",
    "colorado": "Colorado",
    "columbia": "Columbia",
    "irrawaddy": "Irrawaddy",
    "orange": "Oranjerivier",
    "parana": "Paraná",
    "amur": "Amoer",
    "dnieper": "Dnjepr",
    "senegal-river": "Senegal",
    "orinoco": "Orinoco",
    "sao-francisco": "São Francisco",
    "tocantins": "Tocantins",
}

# --- Mountains: id -> Dutch name ------------------------------------------------------------
MOUNTAIN_NAME_NL: dict[str, str] = {
    "himalayas": "Himalaya",
    "andes": "Andes",
    "rockies": "Rocky Mountains",
    "alps": "Alpen",
    "great-dividing-range": "Great Dividing Range",
    "kunlun": "Kunlun",
    "tian-shan": "Tiensjan",
    "altai": "Altai",
    "caucasus": "Kaukasus",
    "pyrenees": "Pyreneeën",
    "carpathians": "Karpaten",
    "appalachians": "Appalachen",
    "atlas": "Atlasgebergte",
    "drakensberg": "Drakensbergen",
    "ethiopian-highlands": "Ethiopisch Hoogland",
    "scandinavian-mountains": "Scandinavisch Hoogland",
    "hindu-kush": "Hindoekoesj",
    "karakoram": "Karakoram",
    "pamir": "Pamir",
    "sierra-nevada-us": "Sierra Nevada",
    "southern-alps": "Zuidelijke Alpen",
    "zagros": "Zagrosgebergte",
    "eastern-rift-highlands": "Hooglanden van de Oost-Afrikaanse Slenk",
}

# --- Seas: id -> Dutch name -----------------------------------------------------------------
SEA_NAME_NL: dict[str, str] = {
    "pacific": "Grote Oceaan",
    "atlantic": "Atlantische Oceaan",
    "indian": "Indische Oceaan",
    "southern": "Zuidelijke Oceaan",
    "arctic": "Noordelijke IJszee",
    "mediterranean": "Middellandse Zee",
    "caribbean": "Caribische Zee",
    "south-china": "Zuid-Chinese Zee",
    "bering": "Beringzee",
    "gulf-of-mexico": "Golf van Mexico",
    "north-sea": "Noordzee",
    "red-sea": "Rode Zee",
    "black-sea": "Zwarte Zee",
    "caspian-sea": "Kaspische Zee",
    "persian-gulf": "Perzische Golf",
    "east-china": "Oost-Chinese Zee",
    "bay-of-bengal": "Golf van Bengalen",
    "arabian-sea": "Arabische Zee",
    "coral-sea": "Koraalzee",
    "tasman-sea": "Tasmanzee",
}


def _insert_after(obj: dict, anchor: str, key: str, value) -> OrderedDict:
    """Return an OrderedDict copy of obj with key/value inserted right after anchor."""
    out: OrderedDict = OrderedDict()
    for k, v in obj.items():
        if k == key:
            continue  # drop any pre-existing nl column so we re-seed cleanly
        out[k] = v
        if k == anchor:
            out[key] = value
    if anchor not in obj:  # anchor missing: append at end
        out[key] = value
    return out


def _seed(filename: str, names: dict[str, str], capitals: dict[str, str] | None) -> None:
    path = RESOURCES / filename
    data = json.loads(path.read_text(encoding="utf-8"))
    missing: list[str] = []
    seeded = []
    for entry in data:
        eid = entry["id"]
        name = names.get(eid)
        if name is None:
            missing.append(eid)
            seeded.append(entry)
            continue
        new_entry = _insert_after(entry, "name_pl", "name_nl", name)
        if capitals is not None:
            cap = capitals.get(eid)
            if cap is None:
                missing.append(f"{eid}(capital)")
            else:
                new_entry = _insert_after(new_entry, "capital_pl", "capital_nl", cap)
        seeded.append(new_entry)
    if missing:
        print(f"FAIL: {filename} missing Dutch for: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)
    path.write_text(json.dumps(seeded, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"seeded nl into {filename} ({len(seeded)} entries)")


def main() -> None:
    _seed("countries.json", COUNTRY_NAME_NL, COUNTRY_CAPITAL_NL)
    _seed("rivers.json", RIVER_NAME_NL, None)
    _seed("mountains.json", MOUNTAIN_NAME_NL, None)
    _seed("seas.json", SEA_NAME_NL, None)


if __name__ == "__main__":
    main()
