#!/usr/bin/env python3
"""One-off (idempotent): seed Italian geo columns into the bundled geo JSON.

Adds ``name_it`` (and ``capital_it`` for countries) to EVERY entity in
``countries.json``/``rivers.json``/``mountains.json``/``seas.json`` — Italian is a
COMPLETE-content language, so coverage is total (zero gaps; the it -> en fallback is a
never-hit safety net).

Translations use established Italian exonyms where they exist (Germania, Spagna, Cina,
Francia, Mosca, Londra, Pechino, Mar Mediterraneo, Mar Rosso, Alpi, Pirenei, Danubio, Reno,
…) and keep the local/native name where Italian has no distinct exonym. The maps below are
keyed by the entity id, so the values are explicit and reviewable.

Idempotent: re-running rewrites the it columns from the same source maps. The ``name_it`` key
is inserted immediately after ``name_yua`` (and ``capital_it`` after ``capital_yua``) so the
JSON stays readable and the it columns sit adjacent to the other per-language columns.

Usage:
    python3 scripts/seed-it-geo.py
"""

from __future__ import annotations

import json
import sys
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCES = REPO_ROOT / "Hanahuac" / "Resources"

# --- Countries: id -> Italian name ----------------------------------------------------------
COUNTRY_NAME_IT: dict[str, str] = {
    # Africa
    "DZ": "Algeria",
    "AO": "Angola",
    "BJ": "Benin",
    "BW": "Botswana",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Capo Verde",
    "CM": "Camerun",
    "CF": "Repubblica Centrafricana",
    "TD": "Ciad",
    "KM": "Comore",
    "CD": "Repubblica Democratica del Congo",
    "DJ": "Gibuti",
    "EG": "Egitto",
    "GQ": "Guinea Equatoriale",
    "ER": "Eritrea",
    "SZ": "Eswatini",
    "ET": "Etiopia",
    "GA": "Gabon",
    "GM": "Gambia",
    "GH": "Ghana",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "CI": "Costa d'Avorio",
    "KE": "Kenya",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "ML": "Mali",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MA": "Marocco",
    "MZ": "Mozambico",
    "NA": "Namibia",
    "NE": "Niger",
    "NG": "Nigeria",
    "CG": "Repubblica del Congo",
    "RW": "Ruanda",
    "ST": "São Tomé e Príncipe",
    "SN": "Senegal",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SO": "Somalia",
    "ZA": "Sudafrica",
    "SS": "Sudan del Sud",
    "SD": "Sudan",
    "TZ": "Tanzania",
    "TG": "Togo",
    "TN": "Tunisia",
    "UG": "Uganda",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    # Asia
    "AF": "Afghanistan",
    "AM": "Armenia",
    "AZ": "Azerbaigian",
    "BH": "Bahrein",
    "BD": "Bangladesh",
    "BT": "Bhutan",
    "BN": "Brunei",
    "KH": "Cambogia",
    "CN": "Cina",
    "CY": "Cipro",
    "GE": "Georgia",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IL": "Israele",
    "JP": "Giappone",
    "JO": "Giordania",
    "KZ": "Kazakistan",
    "KW": "Kuwait",
    "KG": "Kirghizistan",
    "LA": "Laos",
    "LB": "Libano",
    "MY": "Malaysia",
    "MV": "Maldive",
    "MN": "Mongolia",
    "MM": "Myanmar",
    "NP": "Nepal",
    "KP": "Corea del Nord",
    "OM": "Oman",
    "PK": "Pakistan",
    "PH": "Filippine",
    "PS": "Palestina",
    "QA": "Qatar",
    "SA": "Arabia Saudita",
    "SG": "Singapore",
    "KR": "Corea del Sud",
    "LK": "Sri Lanka",
    "SY": "Siria",
    "TW": "Taiwan",
    "TJ": "Tagikistan",
    "TH": "Thailandia",
    "TL": "Timor Est",
    "TR": "Turchia",
    "TM": "Turkmenistan",
    "AE": "Emirati Arabi Uniti",
    "UZ": "Uzbekistan",
    "VN": "Vietnam",
    "YE": "Yemen",
    # Europe
    "AL": "Albania",
    "AD": "Andorra",
    "AT": "Austria",
    "BY": "Bielorussia",
    "BE": "Belgio",
    "BA": "Bosnia ed Erzegovina",
    "BG": "Bulgaria",
    "HR": "Croazia",
    "CZ": "Cechia",
    "DK": "Danimarca",
    "EE": "Estonia",
    "FI": "Finlandia",
    "FR": "Francia",
    "DE": "Germania",
    "GR": "Grecia",
    "HU": "Ungheria",
    "IS": "Islanda",
    "IE": "Irlanda",
    "IT": "Italia",
    "XK": "Kosovo",
    "LV": "Lettonia",
    "LI": "Liechtenstein",
    "LT": "Lituania",
    "LU": "Lussemburgo",
    "MT": "Malta",
    "MD": "Moldavia",
    "MC": "Monaco",
    "ME": "Montenegro",
    "NL": "Paesi Bassi",
    "MK": "Macedonia del Nord",
    "NO": "Norvegia",
    "PL": "Polonia",
    "PT": "Portogallo",
    "RO": "Romania",
    "RU": "Russia",
    "SM": "San Marino",
    "RS": "Serbia",
    "SK": "Slovacchia",
    "SI": "Slovenia",
    "ES": "Spagna",
    "SE": "Svezia",
    "CH": "Svizzera",
    "UA": "Ucraina",
    "GB": "Regno Unito",
    "VA": "Città del Vaticano",
    # North America
    "AG": "Antigua e Barbuda",
    "BS": "Bahamas",
    "BB": "Barbados",
    "BZ": "Belize",
    "CA": "Canada",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "DM": "Dominica",
    "DO": "Repubblica Dominicana",
    "SV": "El Salvador",
    "GD": "Grenada",
    "GT": "Guatemala",
    "HT": "Haiti",
    "HN": "Honduras",
    "JM": "Giamaica",
    "MX": "Messico",
    "NI": "Nicaragua",
    "PA": "Panama",
    "KN": "Saint Kitts e Nevis",
    "LC": "Santa Lucia",
    "VC": "Saint Vincent e Grenadine",
    "TT": "Trinidad e Tobago",
    "US": "Stati Uniti d'America",
    # Oceania
    "AU": "Australia",
    "FJ": "Figi",
    "KI": "Kiribati",
    "MH": "Isole Marshall",
    "FM": "Micronesia",
    "NR": "Nauru",
    "NZ": "Nuova Zelanda",
    "PW": "Palau",
    "PG": "Papua Nuova Guinea",
    "WS": "Samoa",
    "SB": "Isole Salomone",
    "TO": "Tonga",
    "TV": "Tuvalu",
    "VU": "Vanuatu",
    # South America
    "AR": "Argentina",
    "BO": "Bolivia",
    "BR": "Brasile",
    "CL": "Cile",
    "CO": "Colombia",
    "EC": "Ecuador",
    "GY": "Guyana",
    "PY": "Paraguay",
    "PE": "Perù",
    "SR": "Suriname",
    "UY": "Uruguay",
    "VE": "Venezuela",
}

# --- Countries: id -> Italian capital -------------------------------------------------------
COUNTRY_CAPITAL_IT: dict[str, str] = {
    # Africa
    "DZ": "Algeri",
    "AO": "Luanda",
    "BJ": "Porto-Novo",
    "BW": "Gaborone",
    "BF": "Ouagadougou",
    "BI": "Gitega",
    "CV": "Praia",
    "CM": "Yaoundé",
    "CF": "Bangui",
    "TD": "N'Djamena",
    "KM": "Moroni",
    "CD": "Kinshasa",
    "DJ": "Gibuti",
    "EG": "Il Cairo",
    "GQ": "Malabo",
    "ER": "Asmara",
    "SZ": "Mbabane",
    "ET": "Addis Abeba",
    "GA": "Libreville",
    "GM": "Banjul",
    "GH": "Accra",
    "GN": "Conakry",
    "GW": "Bissau",
    "CI": "Yamoussoukro",
    "KE": "Nairobi",
    "LS": "Maseru",
    "LR": "Monrovia",
    "LY": "Tripoli",
    "MG": "Antananarivo",
    "MW": "Lilongwe",
    "ML": "Bamako",
    "MR": "Nouakchott",
    "MU": "Port Louis",
    "MA": "Rabat",
    "MZ": "Maputo",
    "NA": "Windhoek",
    "NE": "Niamey",
    "NG": "Abuja",
    "CG": "Brazzaville",
    "RW": "Kigali",
    "ST": "São Tomé",
    "SN": "Dakar",
    "SC": "Victoria",
    "SL": "Freetown",
    "SO": "Mogadiscio",
    "ZA": "Pretoria",
    "SS": "Giuba",
    "SD": "Khartum",
    "TZ": "Dodoma",
    "TG": "Lomé",
    "TN": "Tunisi",
    "UG": "Kampala",
    "ZM": "Lusaka",
    "ZW": "Harare",
    # Asia
    "AF": "Kabul",
    "AM": "Erevan",
    "AZ": "Baku",
    "BH": "Manama",
    "BD": "Dacca",
    "BT": "Thimphu",
    "BN": "Bandar Seri Begawan",
    "KH": "Phnom Penh",
    "CN": "Pechino",
    "CY": "Nicosia",
    "GE": "Tbilisi",
    "IN": "Nuova Delhi",
    "ID": "Giacarta",
    "IR": "Teheran",
    "IQ": "Baghdad",
    "IL": "Gerusalemme",
    "JP": "Tokyo",
    "JO": "Amman",
    "KZ": "Astana",
    "KW": "Kuwait City",
    "KG": "Bishkek",
    "LA": "Vientiane",
    "LB": "Beirut",
    "MY": "Kuala Lumpur",
    "MV": "Malé",
    "MN": "Ulan Bator",
    "MM": "Naypyidaw",
    "NP": "Kathmandu",
    "KP": "Pyongyang",
    "OM": "Mascate",
    "PK": "Islamabad",
    "PH": "Manila",
    "PS": "Ramallah",
    "QA": "Doha",
    "SA": "Riad",
    "SG": "Singapore",
    "KR": "Seul",
    "LK": "Sri Jayawardenepura Kotte",
    "SY": "Damasco",
    "TW": "Taipei",
    "TJ": "Dušanbe",
    "TH": "Bangkok",
    "TL": "Dili",
    "TR": "Ankara",
    "TM": "Aşgabat",
    "AE": "Abu Dhabi",
    "UZ": "Tashkent",
    "VN": "Hanoi",
    "YE": "Sana'a",
    # Europe
    "AL": "Tirana",
    "AD": "Andorra la Vella",
    "AT": "Vienna",
    "BY": "Minsk",
    "BE": "Bruxelles",
    "BA": "Sarajevo",
    "BG": "Sofia",
    "HR": "Zagabria",
    "CZ": "Praga",
    "DK": "Copenaghen",
    "EE": "Tallinn",
    "FI": "Helsinki",
    "FR": "Parigi",
    "DE": "Berlino",
    "GR": "Atene",
    "HU": "Budapest",
    "IS": "Reykjavík",
    "IE": "Dublino",
    "IT": "Roma",
    "XK": "Pristina",
    "LV": "Riga",
    "LI": "Vaduz",
    "LT": "Vilnius",
    "LU": "Lussemburgo",
    "MT": "La Valletta",
    "MD": "Chișinău",
    "MC": "Monaco",
    "ME": "Podgorica",
    "NL": "Amsterdam",
    "MK": "Skopje",
    "NO": "Oslo",
    "PL": "Varsavia",
    "PT": "Lisbona",
    "RO": "Bucarest",
    "RU": "Mosca",
    "SM": "San Marino",
    "RS": "Belgrado",
    "SK": "Bratislava",
    "SI": "Lubiana",
    "ES": "Madrid",
    "SE": "Stoccolma",
    "CH": "Berna",
    "UA": "Kiev",
    "GB": "Londra",
    "VA": "Città del Vaticano",
    # North America
    "AG": "Saint John's",
    "BS": "Nassau",
    "BB": "Bridgetown",
    "BZ": "Belmopan",
    "CA": "Ottawa",
    "CR": "San José",
    "CU": "L'Avana",
    "DM": "Roseau",
    "DO": "Santo Domingo",
    "SV": "San Salvador",
    "GD": "Saint George's",
    "GT": "Città del Guatemala",
    "HT": "Port-au-Prince",
    "HN": "Tegucigalpa",
    "JM": "Kingston",
    "MX": "Città del Messico",
    "NI": "Managua",
    "PA": "Panama",
    "KN": "Basseterre",
    "LC": "Castries",
    "VC": "Kingstown",
    "TT": "Port of Spain",
    "US": "Washington",
    # Oceania
    "AU": "Canberra",
    "FJ": "Suva",
    "KI": "South Tarawa",
    "MH": "Majuro",
    "FM": "Palikir",
    "NR": "Yaren",
    "NZ": "Wellington",
    "PW": "Ngerulmud",
    "PG": "Port Moresby",
    "WS": "Apia",
    "SB": "Honiara",
    "TO": "Nuku'alofa",
    "TV": "Funafuti",
    "VU": "Port Vila",
    # South America
    "AR": "Buenos Aires",
    "BO": "Sucre",
    "BR": "Brasília",
    "CL": "Santiago del Cile",
    "CO": "Bogotá",
    "EC": "Quito",
    "GY": "Georgetown",
    "PY": "Asunción",
    "PE": "Lima",
    "SR": "Paramaribo",
    "UY": "Montevideo",
    "VE": "Caracas",
}

# --- Rivers: id -> Italian name -------------------------------------------------------------
RIVER_NAME_IT: dict[str, str] = {
    "nile": "Nilo",
    "amazon": "Rio delle Amazzoni",
    "yangtze": "Fiume Azzurro",
    "mississippi": "Mississippi",
    "yenisei": "Enisej",
    "yellow-river": "Fiume Giallo",
    "ob": "Ob'",
    "congo": "Congo",
    "lena": "Lena",
    "niger": "Niger",
    "mekong": "Mekong",
    "missouri": "Missouri",
    "volga": "Volga",
    "zambezi": "Zambesi",
    "ganges": "Gange",
    "indus": "Indo",
    "murray": "Murray",
    "euphrates": "Eufrate",
    "tigris": "Tigri",
    "rhine": "Reno",
    "danube": "Danubio",
    "colorado": "Colorado",
    "columbia": "Columbia",
    "irrawaddy": "Irrawaddy",
    "orange": "Orange",
    "parana": "Paraná",
    "amur": "Amur",
    "dnieper": "Dnepr",
    "senegal-river": "Senegal",
    "orinoco": "Orinoco",
    "sao-francisco": "São Francisco",
    "tocantins": "Tocantins",
}

# --- Mountains: id -> Italian name ----------------------------------------------------------
MOUNTAIN_NAME_IT: dict[str, str] = {
    "himalayas": "Himalaya",
    "andes": "Ande",
    "rockies": "Montagne Rocciose",
    "alps": "Alpi",
    "great-dividing-range": "Grande Catena Divisoria",
    "kunlun": "Monti Kunlun",
    "tian-shan": "Tian Shan",
    "altai": "Monti Altaj",
    "caucasus": "Caucaso",
    "pyrenees": "Pirenei",
    "carpathians": "Carpazi",
    "appalachians": "Monti Appalachi",
    "atlas": "Atlante",
    "drakensberg": "Drakensberg",
    "ethiopian-highlands": "Altopiano Etiopico",
    "scandinavian-mountains": "Alpi Scandinave",
    "hindu-kush": "Hindu Kush",
    "karakoram": "Karakorum",
    "pamir": "Pamir",
    "sierra-nevada-us": "Sierra Nevada",
    "southern-alps": "Alpi Meridionali",
    "zagros": "Monti Zagros",
    "eastern-rift-highlands": "Altopiani della Rift Valley orientale",
}

# --- Seas: id -> Italian name ---------------------------------------------------------------
SEA_NAME_IT: dict[str, str] = {
    "pacific": "Oceano Pacifico",
    "atlantic": "Oceano Atlantico",
    "indian": "Oceano Indiano",
    "southern": "Oceano Antartico",
    "arctic": "Oceano Artico",
    "mediterranean": "Mar Mediterraneo",
    "caribbean": "Mar dei Caraibi",
    "south-china": "Mar Cinese Meridionale",
    "bering": "Mare di Bering",
    "gulf-of-mexico": "Golfo del Messico",
    "north-sea": "Mare del Nord",
    "red-sea": "Mar Rosso",
    "black-sea": "Mar Nero",
    "caspian-sea": "Mar Caspio",
    "persian-gulf": "Golfo Persico",
    "east-china": "Mar Cinese Orientale",
    "bay-of-bengal": "Golfo del Bengala",
    "arabian-sea": "Mar Arabico",
    "coral-sea": "Mar dei Coralli",
    "tasman-sea": "Mar di Tasman",
}


def _insert_after(obj: dict, anchor: str, key: str, value) -> OrderedDict:
    """Return an OrderedDict copy of obj with key/value inserted right after anchor."""
    out: OrderedDict = OrderedDict()
    for k, v in obj.items():
        if k == key:
            continue  # drop any pre-existing it column so we re-seed cleanly
        out[k] = v
        if k == anchor:
            out[key] = value
    if anchor not in obj:  # anchor missing: append at end
        out[key] = value
    return out


def _seed(filename: str, names: dict[str, str], capitals: dict[str, str] | None) -> None:
    path = RESOURCES / filename
    data = json.loads(path.read_text(encoding="utf-8"))
    missing: list[str] = []
    seeded = []
    for entry in data:
        eid = entry["id"]
        name = names.get(eid)
        if name is None:
            missing.append(eid)
            seeded.append(entry)
            continue
        new_entry = _insert_after(entry, "name_yua", "name_it", name)
        if capitals is not None:
            cap = capitals.get(eid)
            if cap is None:
                missing.append(f"{eid}(capital)")
            else:
                new_entry = _insert_after(new_entry, "capital_yua", "capital_it", cap)
        seeded.append(new_entry)
    if missing:
        print(f"FAIL: {filename} missing Italian for: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)
    path.write_text(json.dumps(seeded, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"seeded it into {filename} ({len(seeded)} entries)")


def main() -> None:
    _seed("countries.json", COUNTRY_NAME_IT, COUNTRY_CAPITAL_IT)
    _seed("rivers.json", RIVER_NAME_IT, None)
    _seed("mountains.json", MOUNTAIN_NAME_IT, None)
    _seed("seas.json", SEA_NAME_IT, None)


if __name__ == "__main__":
    main()
